use serde::{Deserialize, Serialize};
use uuid::Uuid;

// Core domain entity representing a user.
// id is kept private with a getter because it is generated by the database layer
// and should never be set directly from outside. sqlx::FromRow enables automatic
// deserialization from PostgreSQL rows into this struct.
#[derive(Clone, Debug, Serialize, Deserialize, sqlx::FromRow)]
pub struct User {
    id: Uuid,
    pub name: String,
    pub email: String,
}

impl User {
    pub fn new(name: String, email: String) -> Self {
        User {
            id: Uuid::new_v4(),
            name,
            email,
        }
    }

    // Constructs a User with a known ID — used when returning updated/deleted
    // entities to the caller without re-querying the database.
    pub fn with_id(id: Uuid, name: String, email: String) -> Self {
        User { id, name, email }
    }

    pub fn id(&self) -> Uuid {
        self.id
    }
}
